services:
  mongodb:
    image: mongo:8.0-noble
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - osm-network
    restart: always

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userservice
      - JWT_SECRET=food_delivery_jwt_secret_2026
    depends_on:
      - mongodb
    networks:
      - osm-network
    restart: always

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/restaurantservice
    depends_on:
      - mongodb
    networks:
      - osm-network
    restart: always

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/orderservice
      - DELIVERY_SERVICE_URL=http://delivery-service:4005
      - NOTIFICATION_SERVICE_URL=http://notification-service:4006
    depends_on:
      - mongodb
    networks:
      - osm-network
    restart: always

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "4004:4004"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/paymentservice
      - ORDER_SERVICE_URL=http://order-service:4003
    depends_on:
      - mongodb
      - order-service
    networks:
      - osm-network
    restart: always

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "4005:4005"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/deliveryservice
      - NOTIFICATION_SERVICE_URL=http://notification-service:4006
    depends_on:
      - mongodb
      - notification-service
    networks:
      - osm-network
    restart: always

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "4006:4006"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/notificationservice
    depends_on:
      - mongodb
    networks:
      - osm-network
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - user-service
      - restaurant-service
      - order-service
      - payment-service
      - delivery-service
      - notification-service
    networks:
      - osm-network
    restart: always

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - user-service
      - restaurant-service
      - order-service
      - payment-service
      - delivery-service
      - notification-service
    networks:
      - osm-network
    restart: always

networks:
  osm-network:
    driver: bridge

volumes:
  mongodb-data:
