events {}

http {
  server {
    listen 80;

    location /api/users/ {
      proxy_pass http://user-service:4001;
    }

    location /api/restaurants/ {
      proxy_pass http://restaurant-service:4002;
    }

    location /api/orders/ {
      proxy_pass http://order-service:4003;
    }

    location /api/payments/ {
      proxy_pass http://payment-service:4004;
    }

    location /api/deliveries/ {
      proxy_pass http://delivery-service:4005;
    }

    location /api/notifications/ {
      proxy_pass http://notification-service:4006;
    }

    location /socket.io/ {
      proxy_pass http://notification-service:4006;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location / {
      proxy_pass http://frontend:80;
    }
  }
}
